version: "3.9"
services:
  coreapp:
    build: coreapp/
    ports:
      - "8080:80"
    env_file:
      - coreapp/coreapp/.env
    depends_on:
      - coredb
      - coreapp-migrate

  coreapp-migrate:
    build: coreapp/
    env_file:
      - coreapp/coreapp/.env
    depends_on:
      - coredb
    command: ["wait-for-it", "coredb:3306", "--", "php", "spark", "migrate"]
    
  coredb:
    build: coredb/
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - coredb/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  db-cli:
    profiles: ["debug"]
    image: mysql:8.0.28-debian
    command: /bin/true
    tty: true
    stdin_open: true 